### ISSUE TITLE
API returns empty response for United States universities

### ISSUE THREAD

**Issue by m-dot-dev** [Hipo/university-domains-list#762]
The API works correctly for most countries and returns either a list of universities or an empty array [] if no universities are found.

However, when querying for universities in the United States, the API returns an empty response instead of a valid list. This is inconsistent behavior because:
	•	There are clearly multiple universities in the United States.
	•	The world_universities_and_domains.json file contains many entries for United States universities.

Steps to Reproduce:
	1.	Call the API with country=United State
`http://universities.hipolabs.com/search?country=United%20States`
	2. Observe that the response is empty (no JSON array).

Expected Behavior:
The API should return a JSON array of universities in the United States (as it does for other countries with data).

Actual Behavior:
The response is completely empty.

Additional Notes:
	•	Example: country=Pakistan or country=Canada works as expected.
	•	world_universities_and_domains.json already contains U.S. universities, so the data source seems fine.
	•	Seems to be working fine locally but not on the deployed api `http://universities.hipolabs.com/search?country=United%20States`

**Comment by ceydaduzgec** [comment]
Hello @m-dot-dev, we deployed the json again this week. I can get a valid response for `http://universities.hipolabs.com/search?country=United%20States ` Can you also check and verify so that I can close this issue?

**Comment by m-dot-dev** [comment]
Hey @ceydaduzgec . Thanks for looking into it. I am still getting the issue. 

No response on `http://universities.hipolabs.com/search?country=United%20States`. 

It returns a blank/empty response ( nothing, not even [] )

**Comment by ceydaduzgec** [comment]
Hello @m-dot-dev can you try `curl http://universities.hipolabs.com/search?country=United%20States` to see if it is working?

**Comment by m-dot-dev** [comment]
Yes it seems to be working via `curl http://universities.hipolabs.com/search?country=United%20States`

**Comment by ceydaduzgec** [comment]
I am still investigating the issue, but I think it is because United States response is returning too much data. And currently there is not pagination. There is another issue related to this: https://github.com/Hipo/university-domains-list/issues/702

**Comment by m-dot-dev** [comment]
Understandable, that the response is not being sent because of too much data in the response. Will we be keeping this issue open till resolution on that part.. 

Thanks for walking me through this.

**Comment by ceydaduzgec** [comment]
@m-dot-dev I will close this one since this repository is only for maintaining the `json` data. I will also close the other issue as well. And reference these two in another issue on `https://github.com/Hipo/university-domains-list-api` repo.
